name: OrangeFox / TWRP Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Checkout Device Tree
      uses: actions/checkout@v4.1.7

    - name: Build Recovery
      uses: SHRP-Devices/Recovery-Builder-Action@main
      with:
        MANIFEST_URL: 'https://github.com/minimal-manifest-twrp/firmware_manifest_twrp'
        MANIFEST_BRANCH: 'twrp-11'
        DEVICE_TREE_URL: 'https://github.com/${{ github.repository }}'
        DEVICE_TREE_BRANCH: 'android-12.1'
        DEVICE_PATH: 'device/samsung/a32'
        DEVICE_NAME: 'a32'
        MAKEFILE_NAME: 'twrp_a32'
        BUILD_TARGET: 'recovery'
